### ISSUE TITLE
add package to yum or any package manager

### ISSUE THREAD

**Issue by nilasuba** [joereynolds/gauxilium#101]
We are trying to install linux version of sql-linter for one my requirement. We find bit difficult in installing sql-lint. Could you please add this in a package manager for linux.
Thanks,

**Comment by joereynolds** [comment]
Hi nilasuba!
If you have `npm` installed, it should be as easy as `npm install sql-lint`.

I will look into packaging it as a `.deb`

**Comment by joereynolds** [comment]
Hey @nilasuba.

If you head to the [releases](https://github.com/joereynolds/sql-lint/releases) page, there are packages there that will work out of the box :)

Here's the latest [linux release](https://github.com/joereynolds/sql-lint/releases/download/v0.0.11/sql-lint-linux)

What part are you finding difficult?

**Comment by nilasuba** [comment]
Hi Joereynolds,

Did we need to create .config file manually? I dont see any folder created after sql-lint installed. Do we need to create a cofig/sql-lint/config.json ?

**Comment by joereynolds** [comment]
Hi @nilasuba,

Yes, you need to create that manually, this should contain the connection details to your database.

Here's an example of mine

```
: cat ~/.config/sql-lint/config.json 
{
    "host": "a.host.db",
    "user": "root",
    "password": "a-random-password"
}
```
The [configuration guide](https://github.com/joereynolds/sql-lint/blob/typescript/doc/configuration.md) is a good starting point.
I hope that helps!

**Comment by nilasuba** [comment]
Do we really need to connect to DB for checking syntax error. ideally we just want to check the sql files for valid syntax, should be possible to do that without a connection to the db

**Comment by joereynolds** [comment]
@nilasuba unfortunately yes. There are some basic checks that will work without connection details but syntax checking is not one of them.

The majority of sql-lint works by sending your query to the server (either MySQL or Postgres), attempting to `EXPLAIN` the query and then reporting back with any errors.

Hope that helps!
