### ISSUE TITLE
"CREATE OR REPLACE TEMPORARY TABLE" failure on "OR"

### ISSUE THREAD

**Issue by dfarrel1** [joereynolds/gauxilium#102]
sql-lint --file="<my-queries>.sql"
output:
```
snowflake_ingestion/sql/features/driver.sql:13 [sql-lint: invalid-create-option] Option 'or' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","procedure","server","table","tablespace","temporary","trigger","user","view"]'.
```

`OR` should be fine.

**Comment by joereynolds** [comment]
Hey @dfarrel1 thanks for the heads up, I'll take a look at this when I get the chance :)

**Comment by joereynolds** [comment]
Hey @dfarrel1 
This has been fixed. There's not going to be another new release for a while so you might want to build from this commit https://github.com/joereynolds/sql-lint/commit/e85622ed42c6167c58350cc28b58909b7bf27530

thanks!
