### ISSUE TITLE
Unable to Categorise DELIMITER statement

### ISSUE THREAD

**Issue by mhanson-vertis** [joereynolds/gauxilium#103]
sql-lint throws the following error when linting file that includes MySQL client command `DELIMITER //`

```
sql-lint\dist\src\lexer\lexer.js:13
    throw new Error(`Unable to categorise query: ${query}. The query must start with one of ${Object.keys(keywords_1.Keyword)}`);
    ^

  );. The query must start with one of Alter,Begin,Call,Create,Declare,Delete,Drop,Else,From,Having,If,Insert,Join,Leave,Limit,Replace,Return,Select,Set,Show,Truncate,Update,Use,Where
```

I also cannot find anything in the documentation that would suggest I can configure the linter to ignore these statements.

**Comment by joereynolds** [comment]
Hey @mhanson-vertis thanks for the report!
Can you give me the query that caused this error too and I can take a look?
I will look into the suggestion of ignoring the statements, thanks!

**Comment by joereynolds** [comment]
Hey @mhanson-vertis,

I've pushed up a fix or this, let me know if it keeps happening.
Thank you!

https://github.com/joereynolds/sql-lint/commit/6cc7b2becdb20e1d5fc30e16e22a06fd8b299638
