### ISSUE TITLE
feature: Use exit codes

### ISSUE THREAD

**Issue by rethab** [joereynolds/gauxilium#107]
When I run the tool and there are errors, the exit code is still 0. Would be nice if it was not so that I can easily integrate it in scripts.

**Comment by joereynolds** [comment]
Good point, this should definitely be done

**Comment by joereynolds** [comment]
Hey @rethab,

Sorry about the delay, this is now done and should be in the next release. Hopefully sometime this week, cheers!

https://github.com/joereynolds/sql-lint/commit/b662e92d668bcf4e1686cfe9c826b3ffbe72bcf0
