### ISSUE TITLE
Feature request: Run this without DB connection

### ISSUE THREAD

**Issue by frmsaul** [joereynolds/gauxilium#109]
Ideally, a linter should run statically without having to talk to the DB. With way you can run it as part of CI. 

Is this a feature that is supported / will be supported in the future?

**Comment by joereynolds** [comment]
Hey frmsaul,

Completely agree and in fact it used to work without a connection for some simple checks and it looks like there's a regression that needs to be fixed first.

It will be supported however the checks that it can do will be a small subset of all of the checks. You get much better results with a connection to the DB as it can then query the server to gather any extra information. Hope that makes sense.

Cheers!

**Comment by frmsaul** [comment]
sounds good! Let me know if I can help somehow.

**Comment by joereynolds** [comment]
Hey @frmsaul,

It won't be in an actual release for a while yet but you can checkout the `typescript` branch and enjoy this now.

Thanks!

01ba7b3768b7f06222baf88c8a026a260e99d059
