### ISSUE TITLE
VSCode integration

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#110]
Hopefully should be quite simple.

See [here](https://blog.lextudio.com/how-a-visual-studio-code-linter-works-681c8388b0ea)

**Comment by nvuillam** [comment]
I struggled a lot recently to integrate npm-groovy-lint into a VsCode Extension, now I have the experience 👍 

I think that if you fork https://github.com/nvuillam/vscode-groovy-lint and replace "groovy" by "sql" , 70% of the work would be done ^^

**Comment by joereynolds** [comment]
Hey @nvuillam 
Thanks for the link, I'll take a look. I don't actually use VSCode so am completely unaware how plugins for it work :smile:
