### ISSUE TITLE
Port option is ignored and cli argument is missing

### ISSUE THREAD

**Issue by rrrnld** [joereynolds/gauxilium#112]
Unfortunately I can't use the tool because it can't establish a connection to the remote server, it throws an error because the connection is rejected. In this error I can see that the standard port (3306) is used instead of the one I configured. I also noticed that `sql-lint -h` does not show an option for port so I couldn't specify it manually either.

My `~/.config/sql-lint/config.json`:
```
{
  "driver": "mysql",
  "host": "HOST",
  "user": "USER",
  "password": "PASS",
  "port": 12345
}
```

**Comment by joereynolds** [comment]
Hey @heyarne,

I've pushed up a fix for the missing `--port` option on the cli. You can now pass `--port` through. As for it not picking up your configuration file, I'm not sure what's going on there as it respects my configuration. I'll have to have a deeper look into that.

Can you confirm if using the `--port` has circumvented the issue for now?

Can you also confirm how you're using `sql-lint`? The `--port` option was only added very recently and isn't in any binary releases. If you want to use it, you'll need to clone this repo and build it yourself. That could be another reason why it's not working.

Cheers!

https://github.com/joereynolds/sql-lint/commit/a193c58a00cfc7cfb393c477723610a47b656d55

**Comment by rrrnld** [comment]
> Can you also confirm how you're using sql-lint? The --port option was only added very recently and isn't in any binary releases. If you want to use it, you'll need to clone this repo and build it yourself. That could be another reason why it's not working.

I'm using it via `npx`, so it should take the latest version on npm I guess? Thanks for responding so quickly!

**Comment by joereynolds** [comment]
Right that makes sense. The `--port` option isn't available in any versions yet, it's still in the master branch, I'll hopefully be creating a new release this week. I'll keep you posted!

**Comment by joereynolds** [comment]
Hey @heyarne, 

A new release has been published onto NPM, there's also a binary release if you prefer that. Cheers!

https://github.com/joereynolds/sql-lint/releases/tag/v0.0.12
