### ISSUE TITLE
--fix should work on stdin

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#124]
Currently the `--fix` command only works when given an argument.

i.e. this works

```
sql-lint --fix "delete from person;"
```

But this doesn't

```
echo "delete from person'" | sql-lint --fix
```

Make it so that it can work from stdin too

**Comment by amitkarpe** [comment]
Hi,

```
root@dev:/src/flyway# sql-lint --fix "delete from person;"
error: unknown option `--fix'
root@dev:/src/flyway# sql-lint -V
0.0.13
```

When I try to run `--fix` flag, it gives an error saying its unknown option.
Do I have to use a different branch? i.e. create-fixer?

**Comment by joereynolds** [comment]
Hi @amitkarpe,

This feature isn't ready yet but it's in the `create-fixer` branch of this project. Don't expect much, it's still very early stages. Cheers!

**Comment by joereynolds** [comment]
Okay new idea. Use nearley and moo for fixing and hand written lexxing/parsing for errors.

Why?

Fixing can only be done on valid SQL (Why would you format broken SQL).

linting errors need to work on broken SQL since that's the whole point of it.

**Comment by joereynolds** [comment]
Hey @amitkarpe,

This has been merged into the main branch (`typescript`). Again, it's still very basic in functionality but at least you can use it off the main branch.

Thanks!

https://github.com/joereynolds/sql-lint/commit/06fce86d1160642a97db585c0b849c30f2d50a91
