### ISSUE TITLE
Postgres' CREATE TYPE not supported

### ISSUE THREAD

**Issue by feuGeneA** [joereynolds/gauxilium#133]
I'd like to use sql-lint on my queries, but upon first try I ran into this problem.

```
$ node_modules/.bin/sql-lint --query "CREATE TYPE my_type AS ENUM('typeA', 'typeb');"
Can't open file /home/gene/.config/sql-lint/config.json. Does it exist?
query:1 [sql-lint: invalid-create-option] Option 'type' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","server","table","tablespace","temporary","trigger","user","unique","view"]'.
```

Then I wondered if specifying a `--driver` would help, guessing maybe that the default is `mysql`?  But that didn't seem to have any effect:

```
$ node_modules/.bin/sql-lint --driver postgres --host localhost --user postgres --password password --query "CREATE TYPE my_type AS ENUM('typeA', 'typeb');"
Can't open file /home/gene/.config/sql-lint/config.json. Does it exist?
query:1 [sql-lint: invalid-create-option] Option 'type' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","server","table","tablespace","temporary","trigger","user","unique","view"]'.
```
(Note that I do have a postgres instance running on localhost:5432, with username/password postgres/password.)

But, I wasn't even sure if that made any sense.  What is the "driver" used for?  Does `sql-lint` connect to the running DB to validate the query?

Is it within scope for `sql-lint` to support this syntax?  If so, what would it take to make that happen?  I would consider creating a PR to do it, but I would need some advice on the application architecture and how this could/should be implemented.

**Comment by joereynolds** [comment]
Hello!

The driver is used as you've said, it connects to the DB to bring back any errors from the server (maybe the documentation should be made more clear). It's not required but will give you more information if it's available.

As for your question, yes it's possible for sql-lint to support this syntax and I'm happy to talk through it.

There are two ways I can think about doing this.

### 1. The quick easy and hacky way

The `options` for a `CREATE` statement are defined in an array in here:
https://github.com/joereynolds/sql-lint/blob/typescript/src/lexer/statements/create.ts

You could add a new item 'TYPE' to that array and be done.
(this will incorrectly allow 'TYPE' as an option in MySQL but I think that's a very small issue that will not come up realistically)

### 2. The nice extensible way

Slightly more involved but allows it to be vendor (Postgres, MySQL etc...) specific in a cleaner way.

In the `src/syntax` directory, create a `postgres/options` directory (making sure it matches the valid `--driver` option which I think is 'postgres') and in there create a file called `create.ts` this will be an array of all of the postgres specific options.

From there you'll need to glue them together. Take a look in this file to see how things are checked

https://github.com/joereynolds/sql-lint/blob/typescript/src/checker/checks/invalidOption.ts

Let me know if you need any more help and thanks for the report

**Comment by withinfocus** [comment]
I started diving into the above modification since we're in need of Postgres support but quickly realized that it would make a lot more sense at an architectural level to extract the `options` element in all these classes to be easily overridden / glued.

If I could make a suggestion it would be to pursue the extraction and set the current values in a base definition somewhere, maybe settling on an even leaner set like ANSI SQL. I am personally too inexperienced with TS to feel comfortable setting that pattern in the best way, but am happy to submit a PR of Postgres definitions for all of them, as well as T-SQL ones.

**Comment by joereynolds** [comment]
Hey @withinfocus,

A PR for the definitions would be good, it doesn't even have to be a TS file, just a text file of each is fine and then I'll try and get around to separating everything out per-driver. This chunk of work is the bottleneck for pretty much everything else so I need to get around to it sooner rather than later.

Thanks for the interest!

**Comment by withinfocus** [comment]
@joereynolds for sure -- any notes on _what_ those boundaries might be? I can hunt around otherwise.

**Comment by joereynolds** [comment]
What do you mean by boundaries? If you mean the things preventing me from doing this, it's just life, other projects, actual work etc...

If you mean the things this is blocking, it's all the vendor specific issues so...

#166
#174 
#177 
#160

**Comment by joereynolds** [comment]
Hey @withinfocus,

I've started documenting the steps required. Feel free to take a stab at it, I hope I'll get a chance soon

https://github.com/joereynolds/sql-lint/issues/178

**Comment by withinfocus** [comment]
I am gonna try to get to this one, got really busy recently!

**Comment by joereynolds** [comment]
Hey @withinfocus, good news is that I started on it and it's mostly there. All that's needed is to (for now) copy over the `mysql` stuff into a `postgres` directory, fix up the tests and add the `TYPE` option to postgres' create

Here's the branch if you wanted to look:
https://github.com/joereynolds/sql-lint/tree/feature/driver-support

**Comment by ChrisScottThomas** [comment]
I want to run this against hiveQL, which feels very similar to SQL.  The only issue we've hit so far is we do:
`CREATE EXTERNAL TABLE`
which returns:
[sql-lint: invalid-create-option] Option 'external' is not a valid option

I assume I can fork this and also just add `"external"` to the options array, but is there a better way of supporting HiveQL going forward?  I guess this would mean a whole new `driver`?

**Comment by joereynolds** [comment]
Hey @ChrisScottThomas,

You're exactly right. As a quick hack just add `external` to the options array. I've got a WIP branch with better driver support. To do it the `proper` way would be to add in `HiveQL` as a separate driver which involves creating a dedicated `HiveQL` directory with its own `Create.ts`, `Delete.ts` etc...

**Comment by ChrisScottThomas** [comment]
> Hey @ChrisScottThomas,
> 
> You're exactly right. As a quick hack just add `external` to the options array. I've got a WIP branch with better driver support. To do it the `proper` way would be to add in `HiveQL` as a separate driver which involves creating a dedicated `HiveQL` directory with its own `Create.ts`, `Delete.ts` etc...

Awesome news.  It's something I will look into when it's ready.
I forked it and am having some issues compiling my changes. 
```
▶ npm run build                                 

> sql-lint@0.0.15 build
> tsc

src/checker/check.ts:1:20 - error TS2307: Cannot find module 'param-case' or its corresponding type declarations.

1 import * as p from "param-case";
```
Amongst many others.  Perhaps this is worth its own issue, unless it's easily explained?  I am  on OSX if that has any impact?

**Comment by joereynolds** [comment]
You're just missing an `npm install` I believe that will fix the issue

**Comment by ChrisScottThomas** [comment]
`npm install --legacy-peer-deps` fixed it for me.  Thank you 👍🏻

**Comment by joereynolds** [comment]
Hey all,

This should now be resolved. Driver support is uch improved, just head to the releases page and check it out 
https://github.com/joereynolds/sql-lint/releases

**Comment by withinfocus** [comment]
Amazing -- really appreciate you finding the time for this, especially when I disappeared! Are there additional needs to build out overrides for Postgres still?

**Comment by joereynolds** [comment]
The only thing you should need to do is specify the driver as `postgres` i.e.

```
sql-lint --driver postgres some-file.sql
```

Then it will know to perform the postgres checks instead of the MySQL ones.

No worries either, I fell upon a lot of spare time recently

**Comment by withinfocus** [comment]
I logged #183 to allow this to be driven via a file which is what's needed for something like the super-linter.
