### ISSUE TITLE
cannot ran without a configuration file

### ISSUE THREAD

**Issue by zvikorn** [joereynolds/gauxilium#134]
Not sure it is an issue. In 0.0.12 release, a code was added to be able to run sql-lint without a configuration file. I still get error msg that it does not exist. Is there a flag I should use?

**Comment by joereynolds** [comment]
Hey @zvikorn,

You shouldn't have to pass any flags through, I'll take a look at this when I can.
Cheers

**Comment by joereynolds** [comment]
Hey @zvikorn,

I've taken a look. This message will always show if you don't have a config file. Simple checks will still be ran.

I could reword it slightly to make the user aware that a better experience is available with a bit more work.

Feel free to re-open this if you're still having issues.
Thanks!

**Comment by zvikorn** [comment]
reopen
