### ISSUE TITLE
Only show 'no config message' when verbose is set

### ISSUE THREAD

**Issue by jpuffer** [joereynolds/gauxilium#136]
I want to use sql-lint for static analysis only (without connecting to a DB.  As far as I can tell from the docs, the config file is optional and only used for DB connections.  However, I cant seem to make the library do that.

`sql-lint -f ./my-file.sql` always returns:
`Can't open file /Users/jake/.config/sql-lint/config.json. Does it exist?`

How can I make this run without trying to make a DB connection?

**Comment by joereynolds** [comment]
Hey @jpuffer,

It will still do the checks regardless of that error, I might consider removing that message as it's created confusion before. That prompt is meant to be helpful but it's mostly confusing. Let me know how it goes

**Comment by joereynolds** [comment]
So a good solution I've arrived at for this which I'll hotfix in when I can is to only show this message when ran with any amount of verbosity (`-v`) flag, should be simple enough

- [ ] - Only display the 'config not found' message when verbose is set

**Comment by jpuffer** [comment]
Thanks for the help.  Looks like most of the files simply passed lint. The error made them appear to fail before linting.
I agree - the message should only some up if verbose is set.  It would also have helped here if there was some success message for files with no problems found.  I'm using this in a CI context on many files at once; I found that adding a little bit of "logging" via shell helps me know what's going on.:
`find . -iname '*.sql' -print0 | xargs -0 -n1 sh -c 'for arg do echo checking "$arg"; sql-lint -d "psql" -f "$arg" && echo code $?; done' _`

That was a lot of work to figure out, so I'll give a big +1 to https://github.com/joereynolds/sql-lint/issues/91 :)

**Comment by joereynolds** [comment]
Hey @jpuffer,

This is complete, it's in the `typescript` branch if you wanted to have it immediately. Failing that, it will be in the upcoming [0.0.14 release](https://github.com/joereynolds/sql-lint/milestone/4)
