### ISSUE TITLE
Add -c flag to point to config file

### ISSUE THREAD

**Issue by admiralAwkbar** [joereynolds/gauxilium#155]
@joereynolds  Hey!

I'm looking at adding this tool to the [GitHub Super-Linter](https://github.com/github/super-linter) and all looks great.

The only issue is I would like to be able to pass a `-c` flag to point to a config file as its run from containers and such, and doesn't have a great `HOME` directory. Not sure the amount of work needed but this would greatly help some developers to help configure as it ran.

thanks!

### Link
https://github.com/github/super-linter/pull/528

**Comment by joereynolds** [comment]
Hey @admiralAwkbar,

Nice idea! I'll try and get this done for the next milestone

**Comment by admiralAwkbar** [comment]
Thank you very much!

**Comment by joereynolds** [comment]
No problem

Note to myself for when I implement this.
Seems pretty simple, do the following:

- [x] - Add a `-c`/`--config` option to specify an alternate config path
- [x] - Update the configuration (line ~52 in `main.ts`) to first try the file specified at `-c` and then falling back to the default one in `~/.config`
- [x] - Add some tests. One to make sure the new option is present. One to make sure the new configuration is actually used/picked up

**Comment by joereynolds** [comment]
Hey @admiralAwkbar,

This is complete. It won't be under a tag for a while yet but if you just want to run off the `typescript` branch that'll have those changes in. Enjoy!

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/commit/66dfbad84fd8432395d6b705fb09285170cecc20

**Comment by joereynolds** [comment]
Hey @admiralAwkbar,

This has been tagged and released as `v0.0.15`. Let me know if you come across any issues.
Thanks!
