### ISSUE TITLE
Unable to install sql-lint on Windows

### ISSUE THREAD

**Issue by nvuillam** [joereynolds/gauxilium#157]
To reproduce, you can just run `npm install sql-lint` on any Windows environment 
I tried : 
- Windows 10 + Bash
- Windows 10 + CMD 
- Windows 10 + Powershell

But the result is always the same

```
> sql-lint@0.0.14 postinstall C:\work\gitPerso\super-linter-2\dependencies\node_modules\sql-lint
> ./build/postinstall.sh

'.' n’est pas reconnu en tant que commande interne
```
( translation in english would be `'.' is an unknown command` )

Please could you provide a patch ? I'm not a sql-lint user, but it makes crash the updates I want to make on GitHub Super Linter :)

Ref: https://github.com/github/super-linter/issues/538#issuecomment-671359033

**Comment by IAmHughes** [comment]
I was able to reproduce this as well:

- Windows 10 Pro + Git Bash (git v2.26.1.windows.1)

I got the exact same error as well. Seems there may be a problem specifically with Windows as this works fine on my Macbook Pro.

**Comment by joereynolds** [comment]
Hey both (@nvuillam + @IAmHughes )

Admittedly, the windows build doesn't get much love. I'll take a look at this soon to see what's happening!
Thanks

**Comment by joereynolds** [comment]
Hey both (@nvuillam + @IAmHughes ) again,
This has been done in the newest release (v0.0.15).
Let me know if any issues arise again.
Thanks!

**Comment by nvuillam** [comment]
@joereynolds Works great, thanks a lot ! 😃

**Comment by nvuillam** [comment]
FYI, Github super-linter now uses your newest version of sql-lint :)

https://github.com/github/super-linter/pull/554

**Comment by joereynolds** [comment]
Nice!
Any other problems, let me know
