### ISSUE TITLE
create schema is detected as invalid

### ISSUE THREAD

**Issue by 0xjac** [joereynolds/gauxilium#167]
Trying to lint a file with `CREATE SCHEMA` is considered invalid.

``` shell
echo 'CREATE SCHEMA test;' | sql-lint          
stdin:1 [sql-lint: invalid-create-option] Option 'schema' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","server","table","tablespace","temporary","trigger","user","unique","view"]'.
```
Other  `CREATE` calls such as `CREATE DATABASE` work.

On the other hand, `DROP SCHEMA` works:
```shell
echo 'DROP SCHEMA test;' | sql-lint
```

**Comment by joereynolds** [comment]
My mistake, must've missed that from the spec somehow...
Anyway, it's fixed, enjoy!

https://github.com/joereynolds/sql-lint/commit/eb9527a3b3121fe8be05c221d5b009dba8541ce4
