### ISSUE TITLE
sql-lint should show lint violation location

### ISSUE THREAD

**Issue by chinwobble** [joereynolds/gauxilium#171]
Great plugin!

I have been testing out your plugin on a set of spark-SQL files. Everything works okay I just need to add support for it spark-sql specific syntax.

There are 20 files in my sql folder and when I run `sql-lint` it doesn't tell me which file or line number has the violation.

After adding the following lines to make it support spark-sql to the lexer

```typescript
// syntax/keywords.ts
  RefreshTable = "refresh table",
  Optimize = "optimize",
  Vacuum = "vacuum",
```

I still get this error:
```
sql-lint was unable to lint the following query ";".This could be a bug with sql-lint. Visit this URL to create a bug report: https://github.com/joereynolds/sql-lint/issues/new?title=Unable%20to%20lint%20query&body=;
```

It would be nice if the error could tell me which file and line number had the issue.

**Comment by joereynolds** [comment]
Hey @chinwobble,

`sql-lint` does show the location of the error. Here's an example message:

```
test/test-files/test.sql:29 [sql-lint: my-sql-invalid-create-option] Option 'test' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","role","server","schema","table","tablespace","temporary","trigger","user","unique","view"]'.
```

See the `:29`? That's the location. In your case I think we need to do some more work than just adding those keywords.

What exactly is it you're trying to do? Maybe I can help

**Comment by joereynolds** [comment]
Hey @chinwobble,

I understand what you mean now and this has been fixed (better late than never ey?)

https://github.com/joereynolds/sql-lint/commit/0908c5b19e5275be9de339e2d26d3057526687f1

There probably won't be a release for a while so you can just build from master (`typescript` branch) if you want this change in.
Enjoy and thanks for the report!
