### ISSUE TITLE
Binaries for 0.0.15 release and future releases

### ISSUE THREAD

**Issue by shoce** [joereynolds/gauxilium#172]
I see no binaries for v0.0.15 and i hope they will be available for all future releases?

**Comment by joereynolds** [comment]
Hey @shoce,

You're right, I will add them today or tomorrow hopefully. Sorry I didn't see your notification sooner, busy!

**Comment by joereynolds** [comment]
Hey @shoce 
Sorry for the delay, binaries are up!

**Comment by shoce** [comment]
Thanks a lot! ✊🏽
