### ISSUE TITLE
CREATE ROLE statement is considered "not a valid option"

### ISSUE THREAD

**Issue by bcdady** [joereynolds/gauxilium#177]
**Describe the bug**
Running sql-lint (from within [mega-linter](https://github.com/nvuillam/mega-linter)), it throws an error that `[sql-lint: invalid-create-option] Option 'role' is not a valid option`.

**To Reproduce**
1. run sql-lint on a .sql file that contains a statement such as: `CREATE ROLE analyst;`
2. See error

**Error Output**
/tmp/lint/scripts/snowflake_roles.sql:3 [sql-lint: invalid-create-option] Option 'role' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","server","table","tablespace","temporary","trigger","user","unique","view"]'.
/node_modules/sql-lint/dist/src/lexer/lexer.js:14
    throw new Error(`Unable to categorise query: ${query}. The query must start with one of ${Object.keys(keywords_1.Keyword)}`);
    ^

**Expected behavior**
Per [this MySQL article](https://dev.mysql.com/doc/refman/8.0/en/create-role.html), CREATE ROLE is a valid SQL statement

**Additional context**
macOS 11.1
zsh in iTerm2

**Comment by joereynolds** [comment]
Hi @bcdady,

Sorry about the long delay, I believe this should be resolved in the newest release.
Check out the releases page:
https://github.com/joereynolds/sql-lint/releases
