### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by withinfocus** [joereynolds/gauxilium#183]
With the `--driver` capability recently expanding its importance pretty significantly via #179, it'll help if `sql-lint` can support a local file to ... drive that configuration. Parameters upon command invocation won't work with projects like https://github.com/github/super-linter and they prefer local configuration file presence.

Requesting the ability to:

- use a configuration file with `sql-lint` locally, with a default name; YAML or JSON preferred
- support all current command-line parameters in the above configuration file
- support the providing of a configuration file name as a command-line parameter should someone want to override the default

Once this in place other tools can share the capability and allow their own overrides, like the super-linter does with environment variables and GitHub Actions.

**Comment by joereynolds** [comment]
Hey @withinfocus, 
sql-lint already supports a config file. See [here](https://sql-lint.readthedocs.io/en/latest/files/configuration.html). You can also specify an alternate path with the `--config` flag. 

It does all of your above points already, cheers!

**Comment by withinfocus** [comment]
Amazing -- I'll bring this up with the super-linter because overrides aren't supported.

**Comment by withinfocus** [comment]
Filed https://github.com/github/super-linter/issues/1383.
