### ISSUE TITLE
CREATE EXTENSION should be valid

### ISSUE THREAD

**Issue by ahmadnassri** [joereynolds/gauxilium#184]
currently using this through [`super-linter`](https://github.com/github/super-linter/)

and coming across this error:

###### `schema.sql`

```
-- enable extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
```

###### `.github/linters/.sql-config.json`

> _this is the path `super-linter` points to for the config_

```
{
  "driver": "postgres",
  "ignore-errors": [
    "invalid-create-option",
    "postgres-invalid-create-option"
  ]
}
```

when running `super-linter`, I get the following error:

```
sql-lint: postgres-invalid-create-option] Option 'extension' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","or","procedure","role","server","schema","table","tablespace","temporary","trigger","type","user","unique","view"]'.
```

`CREATE EXTENSION` is a standard Postgres command, and is needed for cloud providers such as GCP to enable extensions, should be allowed to run ... not sure why this library doesn't let it.

in addition, the `ignore-errors` does not seem to function properly ... (I can verify the JSON config is loaded, as it used to default to `mysql`, but it's correctly detecting `postgres` as the driver)

**Comment by joereynolds** [comment]
Hey @ahmadnassri thanks for the report(s),

I've added the `EXTENSION` keyword. There won't be another release for a while yet but you can build the project from the `typescript` branch and use it.

I've opened another issue to investigate the `ingore-errors` not working
