### ISSUE TITLE
ignore-errors isn't working

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#188]
See here https://github.com/joereynolds/sql-lint/issues/184

Needs some investigation, does it happen on both drivers?

**Comment by johnsandersnl** [comment]
Same for me, ignore-errors is not working. 
My Config (ignoring all errors just to test) looks like this:

{
    "ignore-errors": [
        "odd-code-point",
        "missing-where",
        "invalid-drop-option",
        "invalid-create-option",
        "invalid-truncate-option",
        "invalid-alter-option",
        "hungarian-notation",
        "trailing-whitespace"
    ]
}

Note: 
- Issue occurs when running on latest docker container / in pipeline in Azure Devops.
- The config file is used ( "User provided file:[/tmp/lint/.github/linters/.sql-config.json] exists, setting rules file"). 
  When I add sql server config I get an error about that.

**Comment by joereynolds** [comment]
Thanks for this @johnsandersnl this will definitely help!

**Comment by johnsandersnl** [comment]
Thanks for your fast reply!
I also tested locally with latest super-linter docker image. Errors are also ignored, but this may be easier to reproduce for you.

**Comment by johnsandersnl** [comment]
Additional error info running locally:
2021-08-04 09:55:00 [ERROR]   Error code: 1. Command output:

/tmp/lint/MetadataDb/etl/Stored Procedures/usp_StgToHis.sql:1 [sql-lint: hungarian-notation] Hungarian notation present in query
sql-lint was una, CHAR(10), the 'DROP TABLE IF EXISTS ##TMP_CURRENT_',@OBJECT ,';".This could be a bug with sql-lint. Visit this URL to create a bug report: https://github.com/joereynolds/sql-lint/issues/new?title=Unable%20to%20lint%20query&body='%20%0D%09%09,%20CHAR(10),%09'DROP%20TABLE%20IF%20EXISTS%20##TMP_CURRENT_',@OBJECT%20,';

**Comment by joereynolds** [comment]
Hello @johnsandersnl !

Sorry for the extremely late reply. This has now been fixed in the main (`typescript`) branch.

https://github.com/joereynolds/sql-lint/pull/216

Feel free to open this up if the issue persists
