### ISSUE TITLE
Unable to lint query

### ISSUE THREAD

**Issue by nurikk** [joereynolds/gauxilium#194]
COMMIT

**Comment by joereynolds** [comment]
Hey @nurikk, have you got any more information for this? What was the statement it was unable to lint?

**Comment by nurikk** [comment]
If i lint “COMMIT” linter will fail, but works ok with BEGIN statement

**Comment by joereynolds** [comment]
Hello!

This has been fixed
https://github.com/joereynolds/sql-lint/commit/d8d77cfbdab630dd427b4a931d13b0dcd42d4079

It's not been published via NPM yet though.

Thanks and sorry for the very long delay!
