### ISSUE TITLE
Postgres: false positive for DROP TYPE

### ISSUE THREAD

**Issue by jessealama** [joereynolds/gauxilium#197]
SQL-Lint complains that `DROP TYPE` is bad Postgres. Example SQL:

````
DROP TYPE foo;
````

Error message:

````
sql-lint: postgres-invalid-drop-option] Option 'type' is not a valid option, must be one of '["database","event","function","index","logfile","procedure","schema","server","table","view","tablespace","trigger"]'.
````

But `DROP TYPE` is valid. It's how you drop user-defined data types.

Reference: https://www.postgresql.org/docs/current/sql-droptype.html

**Comment by vinicius73** [comment]
Same error here

**Comment by vinicius73** [comment]
Hi @joereynolds, can you help us with this?

**Comment by jessealama** [comment]
Any traction on this?
