### ISSUE TITLE
Ignore-errors part in config.json doesn't work

### ISSUE THREAD

**Issue by Bidaya0** [joereynolds/gauxilium#202]
First of all, thank you for providing sql-lint, a very useful tool.

I'm trying to integrate sql-lint into github action, but encountered some problems.

it seems the ignore-errors part in config.json doesn't work.
The following is part of the log

```
stdout: {"host":"","user":"root","password":"","driver":"mysql","port":3306,"ignore-errors":["missing-where"]}
Error: Command failed: sql-lint ./test/test1.sql --config=/tmp/config.json

stdout: ./test/test1.sql:2 [sql-lint: missing-where] DELETE statement missing WHERE clause.
```

[https://github.com/Bidaya0/sql-lint-in-action](https://github.com/Bidaya0/sql-lint-in-action)

@joereynolds

**Comment by joereynolds** [comment]
Hello!

Sorry for the extremely late reply. This has now been fixed in the main (`typescript`) branch.

https://github.com/joereynolds/sql-lint/pull/216
