### ISSUE TITLE
False positive for postgres `ALTER SEQUENCE`

### ISSUE THREAD

**Issue by r-bennett** [joereynolds/gauxilium#203]
Valid postgres:
```
ALTER SEQUENCE foo RENAME TO bar
```
(see https://www.postgresql.org/docs/10/sql-altersequence.html)

Which is reported as an error with:
```
Option 'sequence' is not a valid option, must be one of '["column","online","offline","ignore","database","event","function","procedure","server","table","tablespace","view"]'
```

**Comment by joereynolds** [comment]
Hey @r-bennett,

Lookd like this fix was merged by you and this was left open?
Going to close this issue for now but feel free to re-open if you think it's still valid.

Cheers!

**Comment by r-bennett** [comment]
@joereynolds you did the merging 😉

But thanks for merging, all looks good to me now 👍
