### ISSUE TITLE
Unable to lint RENAME TABLE query.

### ISSUE THREAD

**Issue by sam-mowrer-nic** [joereynolds/gauxilium#210]
Received this error during a GitHub Actions run. 

> sql-lint was unable to lint the following query "RENAME TABLE NIC.out_of_stock_emails TO NIC.back_in_stock_subscription;".This could be a bug with sql-lint.

**Comment by joereynolds** [comment]
Looks like a fairly simple one, thanks for the heads up!

**Comment by joereynolds** [comment]
Hey @sam-mowrer-nic 

This has now been resolved. Thanks for the report!

https://github.com/joereynolds/sql-lint/commit/940d3d9a8d7f7b9ffd60e42aeeb5b01c6a34095b
