### ISSUE TITLE
Unable to lint query 'COMMENT ON COLUMN'

### ISSUE THREAD

**Issue by chucoec** [joereynolds/gauxilium#212]
Error happened when I try to lint 'COMMENT ON COLUMN...' query in my Postgresql file.

Example: COMMENT ON COLUMN user_id IS 'test comment';

**Comment by rolivares** [comment]
same here

**Comment by joereynolds** [comment]
Hello!

This has been fixed. It's not released in a version yet but is in master.
Any issues, let me know
:)
