### ISSUE TITLE
ALTER TYPE for postgres should be valid

### ISSUE THREAD

**Issue by patextreme** [joereynolds/gauxilium#237]
An error was raised when encountered `ALTER TYPE .....` statement running `sql-lint` through `megalinter`

__Steps to reproduce__
- create some `.sql` file with `ALTER TYPE foo RENAME TO bar;`
- run megaliter with this option `SQL_SQL_LINT_ARGUMENTS: -d postgres`

__Output__

```text
[sql-lint: postgres-invalid-alter-option] Option 'type' is not a valid option, must be one of '["column","online","offline","ignore","database","event","function","procedure","server","table","tablespace","view"]'.
```

In my case, the `--ignore-errors=postgres-invalid-alter-option` flag was added as a workaround.

__Expected Bahavior__

No error from linter. `ALTER TYPE ...` should be valid. https://www.postgresql.org/docs/current/sql-altertype.html

**Comment by joereynolds** [comment]
Hey @patextreme , this has been fixed. Thanks :)
https://github.com/joereynolds/sql-lint/pull/272
