### ISSUE TITLE
Option 'publication' is not a valid option

### ISSUE THREAD

**Issue by konrad-awsiukiewicz** [joereynolds/gauxilium#240]
[sql-lint: postgres-invalid-create-option] Option 'publication' is not a valid option, must be one of '["algorithm","database","definer","event","extension","function","index","or","procedure","role","sequence","server","schema","table","tablespace","temporary","trigger","type","user","unique","view"]'.

**Comment by joereynolds** [comment]
Hello!
Sorry for the extremely late reply.
I have now added this as an option, cheers!

https://github.com/joereynolds/sql-lint/commit/bcbefc4a85dfb5c65e541e5fae6f11d98c6f8f1e
