### ISSUE TITLE
Does not lint materialized views

### ISSUE THREAD

**Issue by LydiaF** [joereynolds/gauxilium#245]
Hello,

Thank you for your package.

It would be great if it could lint `CREATE MATERIALIZED VIEW`

![photo_2023-04-28_15-11-34](https://user-images.githubusercontent.com/10000865/235171153-46f00fa4-4c52-4535-ac3e-bc93a495be4d.jpg)

Thanks for considering!

**Comment by joereynolds** [comment]
Hey @LydiaF 
What dialect is that, MySQL?

**Comment by LydiaF** [comment]
Hi Joe,

Thanks for answering :)

I have actually since updated the settings to use postgres. However the issue is still there: 
![Screenshot 2023-05-11 at 18 59 15](https://github.com/joereynolds/sql-lint/assets/10000865/59f7c0af-ffd2-4e47-90f8-386107eeeaa6)

Best,

Lydia

**Comment by phrocker** [comment]
I added this: https://github.com/joereynolds/sql-lint/pull/246 

I don't know what I'm doing in the project generally but happy to receive feedback on what I'm missing.

**Comment by YNedderhoff** [comment]
Just here to say that we'd love this to be included as well!

**Comment by joereynolds** [comment]
Hey guys! 
Sorry about the delay, I've just merged in #246. If you build off master you'll be able to use it. Either that or wait until I release a version (not sure when this will be if I'm honest)

Thank you!
