### ISSUE TITLE
Unable to lint query: COMMIT

### ISSUE THREAD

**Issue by gorrelljd21** [joereynolds/gauxilium#251]
Received this while running the lint for a file similar to this:

```
BEGIN;
TRUNCATE TABLE table_1 CASCADE;
TRUNCATE TABLE table_2 CASCADE;
TRUNCATE TABLE table_3 CASCADE;
TRUNCATE TABLE table_4 CASCADE;
COMMIT;
```

Error:

```
sql-lint was unable to lint the following query "COMMIT;".This could be a bug with sql-lint.;
```

Is there a way to ignore certain lines of code so the lint doesn't try to do its thing?

Thanks!

**Comment by joereynolds** [comment]
Hello!

This has been fixed
https://github.com/joereynolds/sql-lint/commit/d8d77cfbdab630dd427b4a931d13b0dcd42d4079

It's not been published via NPM yet though.

Thanks and sorry for the very long delay!
