### ISSUE TITLE
Why is `CREATE TEMPORARY TABLE` allowed but `CREATE TEMP TABLE` not allowed?

### ISSUE THREAD

**Issue by chris-s-friedman** [joereynolds/gauxilium#252]
See title.

In PostgreSQL, `CREATE TABLE` has a parameter to indicate if a table is temporary. Per psql [docs](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-TEMPORARY), this param can either be `TEMPORARY` *or* `TEMP`. 

Per the sql-lint [docs](https://sql-lint.readthedocs.io/en/latest/files/checks.html#invalid-create-option), only `CREATE TEMPORARY TABLE` is allowed but `CREATE TEMP TABLE` is not allowed. 

Why isn't this pattern permitted in sql-lint?

**Comment by joereynolds** [comment]
Closing as resolved by yourself here https://github.com/joereynolds/sql-lint/pull/253
