### ISSUE TITLE
[WIP] Make error message formats consistent

### ISSUE THREAD

**Issue by bencoveney** [joereynolds/gauxilium#60]
### Steps to reproduce

Just using the example from `README.md`

### Actual behaviour

```
test/test.sql:13 Bad code point
test/test.sql:40 Delete missing WHERE, intentional?
test/test.sql:6 Database 'test' does not exist.
test/test.sql:10 Database 'dykes_reservations' does not exist.
test/test.sql:11 Database 'dykes_res' does not exist.
test/test.sql:13 [ER_PARSE_ERROR] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FRO�' at line 1
test/test.sql:16 [ER_NO_DB_ERROR] No database selected
test/test.sql:29 [ER_NO_DB_ERROR] No database selected
test/test.sql:54 [ER_NO_SUCH_TABLE] Table 'symfony.dont_exist' doesn't exist
```

### Expected behaviour

Hi. I found your project from your reddit post. I don't have much to say on the code but thought I could offer some bikeshedding input on the error messages :wink:

When somebody runs your linter my guess is their workflow is something like this:
- See that there is something causing an error.
- Check the message to see if there is details about how to resolve it.
- Resort to using google or CTRL+F in the documentation.

I think there are a couple of improvements you could make to your error messages that might streamline this process for users:
- Add an error code (e.g. `delete-missing-where`) to your error messages to make them easier to look up online.
- Use a consistent tone of voice and sentence structure in the error messages - for example in `Delete missing WHERE, intentional?`:
  - This one is phrased as a question whereas the other error messages are statements.
  - `DELETE` isn't upper-cased whereas `WHERE` is. At a 1second quick glance it almost reads like it is telling me to "delete a WHERE clause that doesn't exist".
  - You could offer a potential description of how to resolve the problem.
- Explicitly distinguish between the linter error messages VS the ones returned by SQL server (this is kinda done because the SQL ones have that error code).

For example - say I use the following structure (just an example):

```
[error-name]
Description of what is wrong.
Potential solution to the problem.
```

This would give the following output:

```
test/test.sql:13 [sql-lint: bad-code-point]
Code-point character is not valid for MySQL.
Replace this to prevent SQL parser errors.

test/test.sql:40 [sql-lint: delete-missing-where]
The DELETE statement has no WHERE clause and will remove all rows in the table.
Add a where clause to prevent accidental data loss.

test/test.sql:6 [sql-lint: missing-database]
Database 'test' does not exist.
Add the database or refer to one that does exist.

test/test.sql:10 [sql-lint: missing-database]
Database 'dykes_reservations' does not exist.
Add the database or refer to one that does exist.

test/test.sql:11 [sql-lint: missing-database]
Database 'dykes_res' does not exist.
Add the database or refer to one that does exist.

test/test.sql:13 [MySQL: ER_PARSE_ERROR]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FRO�' at line 1

test/test.sql:16 [MySQL: ER_NO_DB_ERROR]
No database selected

test/test.sql:29 [MySQL: ER_NO_DB_ERROR]
No database selected

test/test.sql:54 [MySQL: ER_NO_SUCH_TABLE]
Table 'symfony.dont_exist' doesn't exist
```

This would admittedly make the output more verbose - but potentially also more actionable by the user.

Let me know if you would like some contributions on this 👍

**Comment by joereynolds** [comment]
Hey @bencoveney,

Those are all good points, especially on the phrasing of each error. I'm happy for these to be made consistent. As for your point on the format of the messages:

```
test/test.sql:40 Delete missing WHERE, intentional?
```

This is quite a common format (filename:linenumber error) that you'll see in programs like `grep` and it also works almost out of the box with Vim/Emacs etc... which is admittedly why I chose it.
There's two different routes to go down here:

1) Offer a `--vim-format` option (like how `ripgrep` does it) that will leave it in this format so it still 'just works'

2) Fix the vim plugin/patch to work with the new format

Either are acceptable solutions, just thought I'd outline them.

Some of your suggestions (such as a friendly alias for each linter) are in other tickets so I'm hoping with this refactor we could kill two birds with one stone.

It would make it a lot easier to complete #48 if we do your suggested changes.

So yes, I'm happy and open to these contributions :D

Please  note down any pain points you encounter while trying to work on it and I'll try and address them.

**Comment by bencoveney** [comment]
Ah I didn't know about the vim/emacs option. Adding a format option sounds like a good idea 👍 

`--format=vim` or something like that might give some more room for expansion in the future if the project gets a few different formatting options? For example [tslint has a load of them](https://palantir.github.io/tslint/formatters/) so that the output can be used by different tools.

**Comment by joereynolds** [comment]
Hey @bencoveney, 
Off the back of this I've created #64 :+1: 
Let's keep this issue about making the error messages consistent, again, PR's welcome :grin:

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/commit/eb85b41e980facc5f6984a09cd9010728198eea2
