### ISSUE TITLE
Enhancement: Automatically recurse over directories

### ISSUE THREAD

**Issue by mcandre** [joereynolds/gauxilium#91]
When the user supplies a directory path like `.`, then for-loop over the child files. This helps developers to quickly lint large projects that contain many hundreds of .sql files.

**Comment by joereynolds** [comment]
Hey mcandre,

Nice suggestion, can't believe I didn't think of it!

TODO:

- [x] - Use the code in `src/file.ts` to grab all sql files
- [x] - Loop through and lint each one
- [x] - Add an `-r --recurse` option to the CLI

Here's a sample call
```
ext_file_list = recFindByExt("test", "sql");
```

Also it's worth mentioning that with a bit of shell-fu you can already have this functionality

```
find . -iname "*.sql" | xargs -L1 sql-lint -f
```

:)

**Comment by joereynolds** [comment]
Hey @mcandre,

This is now available in the latest commits of `sql-lint` if you want to use it right away. It'll be in the upcoming release otherwise.
Thanks for the suggestion, only took a year!

https://github.com/joereynolds/sql-lint/commit/d199f56627a82460ad970a61f29e6c1c5dc91352
