### ISSUE TITLE
Convention over configuration!

### ISSUE THREAD

**Issue by mcandre** [joereynolds/gauxilium#92]
As a newbie, I want sql-lint to apply a default configuration when none is specified in `$HOME/.config/sql-lint/config.json`, so that I can enjoy using sql-lint immediately out of the box without fussing with the different options.

**Comment by joereynolds** [comment]
Hey @mcandre,

This is done. There's still a warning present about missing a configuration file but you'll get basic errors from `sql-lint` coming through.

Thanks!
