### ISSUE TITLE
Add package to Homebrew

### ISSUE THREAD

**Issue by andrewimeson** [joereynolds/gauxilium#94]
It'd be really handy to be able to install and update the package with [Homebrew](https://brew.sh/). Here's the [guide in the Homebrew docs](https://docs.brew.sh/Formula-Cookbook) for creating a new package.

**Comment by joereynolds** [comment]
I haven't got a mac to test this on so this might prove tricky, PR's welcome though :)

**Comment by brsolomon-deloitte** [comment]
May take a stab at submitting a formula to homebrew-core.

**Comment by brsolomon-deloitte** [comment]
Just installed successfully from homebrew master branch on Mac OS 10.15. This issue can probably be closed?

```
$ brew info sql-lint
sql-lint: stable 0.0.19 (bottled)
SQL linter to do sanity checks on your queries and bring errors back from the DB
https://github.com/joereynolds/sql-lint
/usr/local/Cellar/sql-lint/0.0.19 (1,107 files, 16.7MB) *
  Poured from bottle on 2021-07-30 at 08:42:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sql-lint.rb
License: MIT
==> Dependencies
Required: node ✔
==> Analytics
install: 2 (30 days), 2 (90 days), 0 (365 days)
install-on-request: 2 (30 days), 2 (90 days), 0 (365 days)
build-error: 0 (30 days)
```

For future releases of `sql-lint`, the [formula update](https://docs.brew.sh/Formula-Cookbook) should be pretty easy - the formula lies at https://github.com/Homebrew/homebrew-core/blob/master/Formula/sql-lint.rb.

- Update `url`
- Update `sha256`
- The `bottle` stuff can be [left as-is](https://docs.brew.sh/Formula-Cookbook#updating-formulae)

There are two smoke tests there, one with a `-d postgres` testing an `enum` and one with an invalid `delete` statement.

```
$ brew test -v sql-lint
==> Testing sql-lint
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210730-86544-7ikzoz.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sql-lint.rb --verbose
==> /usr/local/Cellar/sql-lint/0.0.19/bin/sql-lint -d postgres pg-enum.sql
==> /usr/local/Cellar/sql-lint/0.0.19/bin/sql-lint invalid-delete.sql
```

**Comment by joereynolds** [comment]
Yep, thanks again!
Closing.

**Comment by joereynolds** [comment]
@andrewimeson see the thread, your wish has been granted
